services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - redis
      - postgres
      - elasticsearch
    command: python3 manage.py runserver 0.0.0.0:8000

  migration:
    build: .
    command: python3 manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - postgres

  redis:
    image: "redis:6.0.16"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis_server/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticdata:/var/lib/elastic_search/data

  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "StoreAppDatabase"
    ports:
      - "33745:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  elasticdata:
  redisdata: