services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - redis
      - postgres
      - elasticsearch
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9201
      - ELASTIC_USER=<your-elasticsearch-username>
      - ELASTIC_PASSWORD=<your-elasticsearch-password>

  migration:
    build: .
    command: python3 manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=<your-postgres-username>
      - POSTGRES_PASSWORD=<your-postgres-password>

  redis:
    image: "redis:latest"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=<your-elasticsearch-password>
    ports:
      - "9201:9201"
      - "9301:9301"

  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: <your-postgres-username>
      POSTGRES_PASSWORD: <your-postgres-password>
      POSTGRES_DB: storeAppDatabase
    ports:
      - "33745:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: